imports:
    - { resource: common.yml }

services:
    classes_repository:
        class:              \PHPCD\ClassInfo\ComposerClassmapFileRepository
        arguments:          ['%class_loader%', '@default_pattern_matcher', '@class_info_factory', '@file_info_factory', '@default_logger']

    handler.phpid:
        class:              \PHPCD\PHPID
        arguments:          ['%root%', '@default_logger', '@classes_repository']
        # calls:
        #     - [ index ]

    server.phpid:
        class:              Lvht\MsgpackRpc\ForkServer
        arguments:          [ '@messenger', '@handler.phpid' ]
